---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris-v2
  template:
    metadata:
      labels:
        app: tetris-v2
    spec:
      containers:
      - name: tetris
        image: 540979843391.dkr.ecr.us-east-1.amazonaws.com/dockerimages:2
        ports:
        - containerPort: 3000
